In [1]:
# Task 1: Import and Clean Data

In [2]:
# Import relevant Python libraries for data manipulation and numerical operations:
#pandas, numpy, matplotlib, seaborn
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns

In [3]:
#Load the dataset into a Pandas DataFrame from a CSV file. Filename: FloridaBikeRentals.csv
import pandas as pd
df = pd.read_csv('FloridaBikeRentals.csv')
df.head()

,Date,Rented Bike Count,Hour,Temperature,Humidity,Wind speed,Visibility,Dew point temperature,Solar Radiation,Rainfall,Snowfall,Seasons,Holiday,Functioning Day
0,01-12-2017,254,0,-5.2,37,2.2,2000,-17.6,0.0,0.0,0.0,Winter,No Holiday,Yes
1,01-12-2017,204,1,-5.5,38,0.8,2000,-17.6,0.0,0.0,0.0,Winter,No Holiday,Yes
2,01-12-2017,173,2,-6.0,39,1.0,2000,-17.7,0.0,0.0,0.0,Winter,No Holiday,Yes
3,01-12-2017,107,3,-6.2,40,0.9,2000,-17.6,0.0,0.0,0.0,Winter,No Holiday,Yes
4,01-12-2017,78,4,-6.0,36,2.3,2000,-18.6,0.0,0.0,0.0,Winter,No Holiday,Yes

In [4]:
# Inspect the data:
# View the first few rows, shape, column names, and data types
df.info()
df.shape
df.columns
# Identify missing values and inconsistencies
df.isnull().sum()
df.isna().any()
# Handle missing values and data inconsistencies:
# Report missing values and suggest appropriate handling techniques (e.g., fill with mean, drop rows, etc.)
# Check for duplicate records and remove them if necessary
duplicates = df.duplicated()
print(duplicates)
# Comment on data types and suggest optimizations for memory efficiency. Focus on columns such as Temperature, Humidity(%), Wind speed (m/s)
# Convert 'Date' column to datetime
df['Date'] = pd.to_datetime(df['Date'], format='%d-%m-%Y')
# Convert 'Hour' to uint8 to save memory
df['Hour'] = df['Hour'].astype('uint8')
# numeric columns to save memory changing from 64 to as low as data range would allow
df['Temperature'] = df['Temperature'].astype('float32')
df['Wind speed'] = df['Wind speed'].astype('float32')
df['Humidity'] = df['Humidity'].astype('uint8') 
df['Visibility'] = df['Visibility'].astype('int16') 
df['Rented Bike Count'] = df['Rented Bike Count'].astype('int16')
df['Dew point temperature'] = df['Dew point temperature'].astype('float32')
df['Solar Radiation'] = df['Solar Radiation'].astype('float32')
df['Rainfall'] = df['Rainfall'].astype('float32')
df['Snowfall'] = df['Snowfall'].astype('float32')
## NEED TO RESEARCH https://pandas.pydata.org/docs/reference/api/pandas.to_numeric.html - do them automatically in best format
# covert category columns to category from object to save memory
df['Seasons'] = df['Seasons'].astype('category')
df['Holiday'] = df['Holiday'].astype('category')
df['Functioning Day'] = df['Functioning Day'].astype('category')

df.head()
df.info() # run this again, make sure it's good and look at memory usage
## change df name to cleaned_data
# Assume df is your cleaned DataFrame


# Export the cleaned data to JSON format as bike_rental_cleaned.json
df.to_json("bike_rentals_cleaned.json", orient="records", date_format="iso")

# Write a short report summarizing observations about the data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8760 entries, 0 to 8759
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Date                   8760 non-null   object
 1   Rented Bike Count      8760 non-null   int64
 2   Hour                   8760 non-null   int64
 3   Temperature            8760 non-null   float64
 4   Humidity               8760 non-null   int64
 5   Wind speed             8760 non-null   float64
 6   Visibility             8760 non-null   int64
 7   Dew point temperature  8760 non-null   float64
 8   Solar Radiation        8760 non-null   float64
 9   Rainfall               8760 non-null   float64
 10  Snowfall               8760 non-null   float64
 11  Seasons                8760 non-null   object
 12  Holiday                8760 non-null   object
 13  Functioning Day        8760 non-null   object
dtypes: float64(6), int64(4), object(4)
memory usage: 958.3+ KB
0       False
1       False
2       False
3       False
4       False
        ...
8755    False
8756    False
8757    False
8758    False
8759    False
Length: 8760, dtype: bool
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8760 entries, 0 to 8759
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Date                   8760 non-null   datetime64[ns]
 1   Rented Bike Count      8760 non-null   int16
 2   Hour                   8760 non-null   uint8
 3   Temperature            8760 non-null   float32
 4   Humidity               8760 non-null   uint8
 5   Wind speed             8760 non-null   float32
 6   Visibility             8760 non-null   int16
 7   Dew point temperature  8760 non-null   float32
 8   Solar Radiation        8760 non-null   float32
 9   Rainfall               8760 non-null   float32
 10  Snowfall               8760 non-null   float32
 11  Seasons                8760 non-null   category
 12  Holiday                8760 non-null   category
 13  Functioning Day        8760 non-null   category
dtypes: category(3), datetime64[ns](1), float32(6), int16(2), uint8(2)
memory usage: 351.3 KB

In [5]:
# Task 2: Data Processing and Statistical Analysis
raw_df = df.copy()
# Perform transformations:
# Multiply Temperature by 10 for standardization
df['Temperature'] = df['Temperature'] * 10
print(df['Temperature'])

# Scale Visibility to a range between 0 and 1 using MinMax scaling
df['Visibility'] = (df['Visibility'] - df['Visibility'].min()) / (df['Visibility'].max() - df['Visibility'].min())
print(df['Visibility'])

0      -52.0
1      -55.0
2      -60.0
3      -62.0
4      -60.0
        ...
8755    42.0
8756    34.0
8757    26.0
8758    21.0
8759    19.0
Name: Temperature, Length: 8760, dtype: float32
0       1.000000
1       1.000000
2       1.000000
3       1.000000
4       1.000000
          ...
8755    0.946275
8756    1.000000
8757    0.983781
8758    0.928535
8759    0.953877
Name: Visibility, Length: 8760, dtype: float64

In [6]:
# Conduct basic statistical analysis:
# Descriptive statistics for key columns in the transformed dataset


print("Transformed Data Statistics:")
print(df[['Temperature', 'Humidity', 'Rented Bike Count']].describe())

# Descriptive statistics for key columns in the raw dataset
print("\nRaw Data Statistics:")
print(raw_df[['Temperature', 'Humidity', 'Rented Bike Count']].describe())

# Identify columns that are not suitable for statistical analysis and recommend possible datatype changes
# Export the processed data to a CSV file named bike_rental_processed.csv
# Prepare a short report on statistical observations and insights

Transformed Data Statistics:
       Temperature     Humidity  Rented Bike Count
count  8760.000000  8760.000000        8760.000000
mean    128.829224    58.226256         704.602055
std     119.448181    20.362413         644.997468
min    -178.000000     0.000000           0.000000
25%      35.000000    42.000000         191.000000
50%     137.000000    57.000000         504.500000
75%     225.000000    74.000000        1065.250000
max     394.000000    98.000000        3556.000000

Raw Data Statistics:
       Temperature     Humidity  Rented Bike Count
count  8760.000000  8760.000000        8760.000000
mean     12.882922    58.226256         704.602055
std      11.944813    20.362413         644.997468
min     -17.799999     0.000000           0.000000
25%       3.500000    42.000000         191.000000
50%      13.700000    57.000000         504.500000
75%      22.500000    74.000000        1065.250000
max      39.400002    98.000000        3556.000000

In [7]:
# Task 3: Data Analysis with Pandas

# Identify categorical and numerical variables # Focus on columns such as Seasons, Holiday, and Functioning Day
# Perform pivoting operations on the dataset based on categorical columns: Group by Seasons and calculate the average rented bike count
# Analyze trends across Holiday and Functioning Day
# Create distribution tables:# Temperatureand Rented Bike Count distribution by Hour, Seasons and Rented Bike Count distribution
# Encode categorical variables and save data as "Rental_Bike_Data_Dummy.csv"

In [8]:
# Task 4: Data Visualization

# Import visualization libraries (matplotlib, seaborn)
# Select appropriate visualization techniques for the data:
# Bar plot for average rentals by Seasons
# Line plot showing hourly rentals throughout the day
# Heatmap showing correlation among numerical variables
# Box plot to identify outliers in Temperature and Rented Bike Count
# Record observations and insights from visualizations
# Save plots and observations for reporting purposes